const ADD_MOVIE = "ADD_MOVIE";
const DELETE_MOVIE = "DELETE_MOVIE";
const UPDATE_MOVIE = "UPDATE_MOVIE";
const TOGGLE_FAV = "TOGGLE_FAV";
const TOGGLE_UPDATE = "TOGGLE_UPDATE";

export {ADD_MOVIE, DELETE_MOVIE, UPDATE_MOVIE, TOGGLE_FAV, TOGGLE_UPDATE};